#
# This is the reduced environment_ci.yml used for automated test/builds
# There is a primary conda environment.yml for development
# Do NOT FORGET to update both when making changes to this file
#
channels:
  - sofar_fw
  - conda-forge
  - memfault
  - defaults
dependencies:
  # Don't forget to update compiler version check when updating compiler here!
  # Change COMPILER_VERSION near top of src/CMakeLists.txt
  - arm-none-eabi-gcc=13.2
  - clang-tools=18.1
  - cmake=3.29
  - cppcheck
  - gcovr
  - make=4.3
  - pre_commit
  - pyserial
  - python=3.12
  - pip
  - pip:
      - cbor2
      - click
      - cryptography>=42.0
      - gitpython
      - intelhex
      - memfault-cli==1.0
      - pytest
      - python-dotenv
      - bitstring==4.2
      - pyserial
      - regex
      - func_timeout
      - pytest-order
      - crcmod
