#include "external_flash_partitions.h"

#define SECTOR_BUFFER_BYTES                   (4096)

#define HARDWARE_CONFIG_FLASH_OFFSET_BYTES    (0)
#define HARDWARE_CONFIG_FLASH_SIZE_BYTES      (10 * 1024)
#define HARDWARE_CONFIG_FLASH_END_BYTES       (HARDWARE_CONFIG_FLASH_OFFSET_BYTES + HARDWARE_CONFIG_FLASH_SIZE_BYTES)
_Static_assert((HARDWARE_CONFIG_FLASH_OFFSET_BYTES % SECTOR_BUFFER_BYTES == 0), "invalid alignment");

#define SYSTEM_CONFIG_FLASH_OFFSET_BYTES      (HARDWARE_CONFIG_FLASH_END_BYTES + (HARDWARE_CONFIG_FLASH_END_BYTES % SECTOR_BUFFER_BYTES))
#define SYSTEM_CONFIG_FLASH_SIZE_BYTES        (10 * 1024)
#define SYSTEM_CONFIG_FLASH_END_BYTES         (SYSTEM_CONFIG_FLASH_OFFSET_BYTES + SYSTEM_CONFIG_FLASH_SIZE_BYTES)
_Static_assert((SYSTEM_CONFIG_FLASH_OFFSET_BYTES >= HARDWARE_CONFIG_FLASH_END_BYTES), "Invalid flash range");
_Static_assert((SYSTEM_CONFIG_FLASH_OFFSET_BYTES % SECTOR_BUFFER_BYTES == 0), "invalid alignment");

#define USER_CONFIG_FLASH_OFFSET_BYTES        (SYSTEM_CONFIG_FLASH_END_BYTES + (SYSTEM_CONFIG_FLASH_END_BYTES % SECTOR_BUFFER_BYTES))
#define USER_CONFIG_FLASH_SIZE_BYTES          (10 * 1024)
#define USER_CONFIG_FLASH_END_BYTES           (USER_CONFIG_FLASH_OFFSET_BYTES + USER_CONFIG_FLASH_SIZE_BYTES)
_Static_assert((USER_CONFIG_FLASH_OFFSET_BYTES >= SYSTEM_CONFIG_FLASH_END_BYTES), "Invalid flash range");
_Static_assert((USER_CONFIG_FLASH_OFFSET_BYTES % SECTOR_BUFFER_BYTES == 0), "invalid alignment");

#define CLI_CONFIG_FLASH_OFFSET_BYTES         (USER_CONFIG_FLASH_END_BYTES + (USER_CONFIG_FLASH_END_BYTES % SECTOR_BUFFER_BYTES))
#define CLI_CONFIG_FLASH_SIZE_BYTES           (10 * 1024) 
#define CLI_CONFIG_FLASH_END_BYTES            (CLI_CONFIG_FLASH_OFFSET_BYTES + CLI_CONFIG_FLASH_SIZE_BYTES)
_Static_assert((CLI_CONFIG_FLASH_OFFSET_BYTES >= USER_CONFIG_FLASH_END_BYTES), "Invalid flash range");
_Static_assert((CLI_CONFIG_FLASH_OFFSET_BYTES % SECTOR_BUFFER_BYTES == 0), "invalid alignment");

#define DFU_CONFIG_FLASH_OFFSET_BYTES         (CLI_CONFIG_FLASH_END_BYTES + (CLI_CONFIG_FLASH_END_BYTES % SECTOR_BUFFER_BYTES))
#define DFU_CONFIG_FLASH_SIZE_BYTES           (2 * 1000 * 1024) // 2MB
#define DFU_CONFIG_FLASH_END_BYTES            (DFU_CONFIG_FLASH_OFFSET_BYTES + DFU_CONFIG_FLASH_SIZE_BYTES)
_Static_assert((DFU_CONFIG_FLASH_OFFSET_BYTES >= CLI_CONFIG_FLASH_END_BYTES), "Invalid flash range");
_Static_assert((DFU_CONFIG_FLASH_OFFSET_BYTES % SECTOR_BUFFER_BYTES == 0), "invalid alignment");

const ext_flash_partition_t hardware_configuration = {
    .fa_off = HARDWARE_CONFIG_FLASH_OFFSET_BYTES,
    .fa_size = HARDWARE_CONFIG_FLASH_SIZE_BYTES,
};

const ext_flash_partition_t system_configuration = {
    .fa_off = SYSTEM_CONFIG_FLASH_OFFSET_BYTES,
    .fa_size = SYSTEM_CONFIG_FLASH_SIZE_BYTES,
};

const ext_flash_partition_t user_configuration = {
    .fa_off = USER_CONFIG_FLASH_OFFSET_BYTES,
    .fa_size = USER_CONFIG_FLASH_SIZE_BYTES,
};

const ext_flash_partition_t cli_configuration = {
    .fa_off = CLI_CONFIG_FLASH_OFFSET_BYTES,
    .fa_size = CLI_CONFIG_FLASH_SIZE_BYTES,
};

const ext_flash_partition_t dfu_configuration = {
    .fa_off = DFU_CONFIG_FLASH_OFFSET_BYTES,
    .fa_size = DFU_CONFIG_FLASH_SIZE_BYTES,
};
